blank_issues_enabled: false
contact_links:
  - name: Project Discussions
    url: https://github.com/OneFrankDesign/media-api-architecture/discussions
    about: Use discussions for questions and design conversation.
